{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(total_requests[5m]))\r\n",
     "legendFormat": "Request per second"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "request_latency_seconds_sum", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Hits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(total_requests)\r\n", "legendFormat": "Total Request" },
    { "expr": "sum(success_hits)", "legendFormat": "Success Hits" },
    { "expr": "sum(failure_hits)", "legendFormat": "Failure Hits" }
   ]
  }
 ]
}